var contactData = [
  {
    "showName":"Thomas Sun",
    "showName_followup":"(GAUSIAN)",
    "hasName":true,
    "first":"Thomas",
    "last":"Sun",
    "hasCompany":true,
    "company":"GAUSIAN",
    "privateDomain":true,
    "email":"ceo@gausian.com",
    "mobile":"(408)601-9098",
    "display":true,
    "active":true,
  },
  {
    "showName":"Alex Song",    
    "showName_followup":"",
    "hasName":true,
    "first":"Ales",
    "last":"Song",
    "hasCompany":false,
    "privateDomain":false,
    "email":"alex.song@outlook.com",
    "mobile":"(408)601-9098",
    "display":true,
    "active":true,
  },
  {
    "showName":"David Huang",     
    "showName_followup":"(Apple)",
    "hasName":true,
    "first":"David",
    "last":"Huang",
    "hasCompany":true,
    "company":"Apple",
    "privateDomain":true,
    "email":"david.huang@app.com",
    "mobile":"(408)601-9098",
    "display":true,
    "active":true,
  },
  {
    "showName":"Jason Wang",   
    "showName_followup":"(Facebook)", 
    "hasName":true,
    "first":"Jason",
    "last":"Wang",
    "hasCompany":true,
    "company":"Facebook",
    "privateDomain":true,
    "email":"jason.wang@facebook.com",
    "mobile":"(408)601-9098",
    "display":true,
    "active":true,
  },
  {
    "showName":"Zhihua Wang", 
    "showName_followup":"(Tsinghua)", 
    "hasName":true,  
    "first":"Zhihua",
    "last":"Wang",
    "hasCompany":true,
    "company":"Tsinghua",
    "privateDomain":true,
    "email":"zhihua@tsinghua.edu.cn",
    "mobile":"(408)601-9090",
    "display":true,
    "active":true,
  },
  {
    "showName":"lifwithchip@slack",
    "showName_followup":"", 
    "hasName":false, 
    "hasCompany":true,
    "company":"Slack",
    "privateDomain":true,
    "email":"lifwithchip@slack.com",
    "display":true,
    "active":true,
  },
  {
    "showName":"cattyguan@gmail",
    "showName_followup":"", 
    "hasName":false, 
    "hasCompany":false,
    "privateDomain":false,
    "email":"cattyguan@gmail.com",
    "display":true,
    "active":true,
  },
  {
    "showName":"tianjiasun@gmail",
    "showName_followup":"", 
    "hasName":false, 
    "hasCompany":false,
    "privateDomain":false,
    "email":"tianjiasun@gmail.com",
    "display":true,
    "active":true,
  },
];

var messageData = [
  {
    "inout":"in",
    "from_contact_index":2,
    "from_group_index":null,
    "to_contact_index":0,
    "to_group_index":null,
    "cc_contact_index":null,
    "channel":"Email",
    "time":1288323623006,
    "topic":"Performance Issue",
    "content":"Hi All, there is a performance issue.",
    "attachments_index":null,
    "spam":false,
    "unread":false,
    "display":true,
    "active":true,
  },
  {
    "inout":"in",
    "from_contact_index":2,
    "from_group_index":null,
    "to_contact_index":0,
    "to_group_index":null,
    "cc_contact_index":null,
    "channel":"Email",
    "time":1288327623006,
    "topic":"Performance Issue",
    "content":"Hi All, there is a performance issue.",
    "attachments_index":null,
    "spam":false,
    "unread":false,    
    "display":true,
    "active":true,
  },
  {
    "inout":"in",
    "from_contact_index":2,
    "from_group_index":null,
    "to_contact_index":0,
    "to_group_index":null,
    "cc_contact_index":null,
    "channel":"Email",
    "time":1288223623006,
    "topic":"Performance Issue",
    "content":"Hi All, there is a performance issue.",
    "attachments_index":null,
    "spam":false,
    "unread":false, 
    "display":true,
    "active":true,
  },  
  {
    "inout":"out",
    "from_contact_index":0,
    "from_group_index":null,
    "to_contact_index":2,
    "to_group_index":null,
    "cc_contact_index":null,
    "channel":"Email",
    "time":1281323624006,
    "topic":"Performance Issue",
    "content":"Hi Jason, what do you think about the performance",
    "attachments_index":null,
    "spam":false,    
    "unread":true, 
    "display":true,
    "active":true,
  },
  {
    "inout":"in",
    "from_contact_index":1,
    "from_group_index":null,
    "to_contact_index":0,
    "to_group_index":null,
    "cc_contact_index":null,
    "channel":"Email",
    "time":1288323425009,
    "topic":"spam",
    "content":"Hi All, buy this.",
    "attachments_index":null,
    "spam":true,    
    "unread":true, 
    "display":true,
    "active":true,
  },
  {
    "inout":"in",
    "from_contact_index":1,
    "from_group_index":null,
    "to_contact_index":0,
    "to_group_index":null,
    "cc_contact_index":null,
    "channel":"Signaler",
    "time":1286323526000,
    "topic":"Discussion of Roadmap",
    "content":"Hi there.",
    "attachments_index":null,
    "spam":false,    
    "unread":true, 
    "display":true,
    "active":true,
  },
  {
    "inout":"in",
    "from_contact_index":3,
    "from_group_index":null,
    "to_contact_index":0,
    "to_group_index":null,
    "cc_contact_index":null,
    "channel":"Email",
    "time":1288123528006,
    "topic":"Discussion of Roadmap",
    "content":"Hi All, this is a long message to experiment relative position wount affect others. Sometimes it is amazingly good to go. let's talk about our roadmap later.",
    "attachments_index":0,
    "spam":false,    
    "unread":true, 
    "display":true,
    "active":true,
  },
  {
    "inout":"out",
    "from_contact_index":3,
    "from_group_index":null,
    "to_contact_index":3,
    "to_group_index":null,
    "cc_contact_index":null,
    "channel":"Email",
    "time":1288123628006,
    "topic":"Can someone help me on this angular problem",
    "content":"Hi All, let's talk about our roadmap later.",
    "attachments_index":null,
    "spam":false,    
    "unread":true,
    "display":true,
    "active":true,
  },
  {
    "inout":"in",
    "from_contact_index":2,
    "from_group_index":null,
    "to_contact_index":0,
    "to_group_index":null,
    "cc_contact_index":null,
    "channel":"Email",
    "time":1288312629007,
    "topic":"Discussion of Roadmap",
    "content":"This is a test.",
    "attachments_index":null,
    "spam":false,    
    "unread":true,
    "display":true,
    "active":true,
  },
  {
    "inout":"in",
    "from_contact_index":2,
    "from_group_index":null,
    "to_contact_index":0,
    "to_group_index":null,
    "cc_contact_index":null,
    "channel":"Text",
    "time":1282323929007,
    "topic":"Discussion of Roadmap",
    "content":"This is a test.",
    "attachments_index":null,
    "spam":false,  
    "unread":true,  
    "display":true,
    "active":true,
  },  
  {
    "inout":"out",
    "from_contact_index":0,
    "from_group_index":null,
    "to_contact_index":2,
    "to_group_index":null,
    "cc_contact_index":null,
    "channel":"Email",
    "time":1281323736006,
    "topic":"Performance Issue",
    "content":"Performance will be good",
    "attachments_index":null,
    "spam":false,    
    "unread":true,
    "display":true,
    "active":true,
  },
  {
    "inout":"in",
    "from_contact_index":1,
    "from_group_index":null,
    "to_contact_index":0,
    "to_group_index":null,
    "cc_contact_index":null,
    "channel":"Email",
    "time":1282323425009,
    "topic":"spam",
    "content":"Hi All, buy this.",
    "attachments_index":null,
    "spam":true,    
    "unread":true,
    "display":true,
    "active":true,
  },
  {
    "inout":"in",
    "from_contact_index":1,
    "from_group_index":null,
    "to_contact_index":0,
    "to_group_index":null,
    "cc_contact_index":null,
    "channel":"Signaler",
    "time":1186323526000,
    "topic":"Discussion of Roadmap",
    "content":"Hi there.",
    "attachments_index":null,
    "spam":false,    
    "unread":true,
    "display":true,
    "active":true,
  },
];